### ISSUE TITLE
Commit search results in an error if commit doesn't belong to a pull request

### ISSUE THREAD

**Issue by jasonrudolph** [bswinnerton/github.lbaction#21]
### Observed behavior

If you search for a commit that is not part of a pull request (e.g., [212d9cf4631cd175cc45e1930d141768a87b45f8](https://github.com/bswinnerton/github.lbaction/commit/212d9cf4631cd175cc45e1930d141768a87b45f8)), it results in the following error:

<img width="551" alt="screen shot 2017-02-21 at 8 01 51 am" src="https://cloud.githubusercontent.com/assets/2988/23165849/20aac802-f80c-11e6-8542-ea327d75d9ff.png">

### Expected behavior

If the commit isn't part of a PR, I was thinking that it would take you straight to the commit itself. For example, searching for `212d9cf4631cd175cc45e1930d141768a87b45f8` could take you to:
    https://github.com/bswinnerton/github.lbaction/commit/212d9cf4631cd175cc45e1930d141768a87b45f8

If that's not feasible, it would be nice to gracefully handle the error and inform the user that there is no pull request with the given commit.

**Comment by bswinnerton** [comment]
Nice catch, @jasonrudolph! I could have swore that I tested this manually, but I don't yet have unit tests for the `Commit#pullRequests` method.

Once https://github.com/bswinnerton/github.lbaction/issues/20 is addressed, it should add a more graceful error message, but I really love the idea of going straight to a commit. We should be able to determine the repository that commit belongs to by using the [`Commit.repository`](https://developer.github.com/early-access/graphql/object/commit/#fields) GraphQL object, which would give us the ability to build the link to 212d9cf.

I'll get started on both of these points shortly.
