### ISSUE TITLE
Can't navigate to a repository with punctuation in the name

### ISSUE THREAD

**Issue by jasonrudolph** [bswinnerton/github.lbaction#38]
Using version ad78ad7e421b0548396b393de968406c983aa76d of this action:

![demo](https://cloud.githubusercontent.com/assets/2988/23314018/0db1ebb6-fa8e-11e6-8cd3-a4954560cb33.gif)

**Comment by bswinnerton** [comment]
Resolved in https://github.com/bswinnerton/github.lbaction/pull/39 ✨.
