### ISSUE TITLE
Add command enter support to go direct to item

### ISSUE THREAD

**Issue by bswinnerton** [bswinnerton/github.lbaction#8]
For example, after typing:

<img width="668" alt="screen shot 2017-02-19 at 12 28 42 am" src="https://cloud.githubusercontent.com/assets/934497/23099664/644b0bc2-f63a-11e6-9d6f-40a6ca8144d3.png">

And hitting `command` + `enter`,

It'd be great if it automatically went to the appropriate page (similar to what this would do):

<img width="668" alt="screen shot 2017-02-19 at 12 29 25 am" src="https://cloud.githubusercontent.com/assets/934497/23099669/7ae312a8-f63a-11e6-8c96-2324c2f8f7fc.png">

**Comment by jasonrudolph** [comment]
@bswinnerton: When I enter a owner/repo name (e.g., `apple/swift`) and hit command+enter, the LaunchBar window disappears, but it doesn't open the repo:

![demo](https://user-images.githubusercontent.com/2988/32134627-fdb87c82-bbbe-11e7-9c97-4a6752f60f39.gif)

Is there any trick to getting this to work correctly? If there's additional information I can provide, please let me know.

**Comment by bswinnerton** [comment]
> Is there any trick to getting this to work correctly?

@jasonrudolph, I suspect that you're hitting <kbd>⌘</kbd> + <kbd>Enter</kbd> before launchbar-github has a chance to fetch all of the repositories that the Apple organization has access to via an API call to GitHub.

Here's a screen capture of an up-to-date version of launchbar-github that has already cached the result of Apple's repositories:

![swift-command-enter](https://user-images.githubusercontent.com/934497/32147025-736fe08a-bcb6-11e7-9080-893c11315178.gif)

A terrible workaround is to wait for the repositories appear before hitting <kbd>⌘</kbd> + <kbd>Enter</kbd>. But I've opened https://github.com/bswinnerton/launchbar-github/issues/87 to explore a better way of accomplishing this.

**Comment by bswinnerton** [comment]
@jasonrudolph: as a total aside, what are you using to showcase which keys you're pressing in your screen recordings?

**Comment by jasonrudolph** [comment]
> I suspect that you're hitting <kbd>⌘</kbd> + <kbd>Enter</kbd> before launchbar-github has a chance to fetch all of the repositories that the Apple organization has access to via an API call to GitHub.

That does seem to be the case. 😇 

I'm looking forward to #87. Thanks for opening that issue.

> what are you using to showcase which keys you're pressing in your screen recordings?

That's [Mouseposé](https://boinx.com/mousepose/overview/). 😄
